version: '3.8'

services:
  rabbitmq:
    build:
      context: ./rabbitmq/
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Puerto para conexiones AMQP
      - "15672:15672" # Puerto para la interfaz web de RabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - app-network

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    container_name: GestorAlmacenApp
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
